//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtomasyonEntities : DbContext
    {
        public OtomasyonEntities()
            : base("name=OtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<araclar> araclars { get; set; }
        public virtual DbSet<kullanici> kullanicis { get; set; }
        public virtual DbSet<musteriler> musterilers { get; set; }
        public virtual DbSet<roller> rollers { get; set; }
        public virtual DbSet<sati> satis { get; set; }
    }
}
