//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musteriler()
        {
            this.satis = new HashSet<sati>();
        }
    
        public int musteriId { get; set; }
        public string adı { get; set; }
        public string soyadı { get; set; }
        public Nullable<System.DateTime> dTarihi { get; set; }
        public string gsm { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public string dYeri { get; set; }
        public string Cinsiyet { get; set; }
        public byte[] resim { get; set; }
        public string tcno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sati> satis { get; set; }
    }
}
