//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar
{
    using System;
    using System.Collections.Generic;
    
    public partial class sati
    {
        public int satisId { get; set; }
        public Nullable<int> musteriId { get; set; }
        public Nullable<int> aracId { get; set; }
        public string tutar { get; set; }
    
        public virtual araclar araclar { get; set; }
        public virtual musteriler musteriler { get; set; }
    }
}
